package:
  name: biogenie
  version: "1.3.0"

source:
  url: https://github.com/mikeph52/BioGenie/archive/refs/tags/v.1.3.0.tar.gz
  sha256: 23d9a40e6f4809c0db53a5efffb531954d679ca905112a465f7ba8734ab815af

build:
  number: 1
  script:
    - mkdir -p $PREFIX/bin # [not win]
    - x86_64-linux-gnu-g++ -std=c++17 -o biogenie_x64 main.cpp -lpthread  # [not win]
    - $CXX -std=c++17 -o $PREFIX/bin/biogenie main.cpp -lpthread  # [not win]
    - if not exist %LIBRARY_BIN% mkdir %LIBRARY_BIN%    # [win]
    - '%CXX% -std=c++17 -Fe:%LIBRARY_BIN%\biogenie.exe main.cpp' # [win]

requirements:
  build:
    - {{ compiler('cxx') }}

about:
  home: https://github.com/mikeph52/BioGenie
  license: GPL-3.0
  summary: "BioGenie is a complete bioinformatics command line tool, written in C++."

extra:
  recipe-maintainers:
    - mikeph52